package com.hp;
// Generated Jul 18, 2015 2:01:20 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Faqs generated by hbm2java
 */
@Entity
@Table(name="faqs"
    ,catalog="stp15_june"
)
public class Faqs  implements java.io.Serializable {


     private Integer faqid;
     private String ques;
     private String ans;

    public Faqs() {
    }

    public Faqs(String ques, String ans) {
       this.ques = ques;
       this.ans = ans;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="faqid", unique=true, nullable=false)
    public Integer getFaqid() {
        return this.faqid;
    }
    
    public void setFaqid(Integer faqid) {
        this.faqid = faqid;
    }

    
    @Column(name="ques", nullable=false, length=100)
    public String getQues() {
        return this.ques;
    }
    
    public void setQues(String ques) {
        this.ques = ques;
    }

    
    @Column(name="ans", nullable=false, length=100)
    public String getAns() {
        return this.ans;
    }
    
    public void setAns(String ans) {
        this.ans = ans;
    }




}


