package com.hp;
// Generated Jul 18, 2015 2:01:20 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name="login"
    ,catalog="stp15_june"
)
public class Login  implements java.io.Serializable {


     private Integer userid;
     private String username;
     private String password;
     private String email;
     private String institutename;
     private String fullname;
     private String repassword;

    public Login() {
    }

    public Login(String username, String password, String email, String institutename, String fullname, String repassword) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.institutename = institutename;
       this.fullname = fullname;
       this.repassword = repassword;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="userid", unique=true, nullable=false)
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    
    @Column(name="username", nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="institutename", nullable=false, length=45)
    public String getInstitutename() {
        return this.institutename;
    }
    
    public void setInstitutename(String institutename) {
        this.institutename = institutename;
    }

    
    @Column(name="fullname", nullable=false, length=45)
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    
    @Column(name="repassword", nullable=false, length=45)
    public String getRepassword() {
        return this.repassword;
    }
    
    public void setRepassword(String repassword) {
        this.repassword = repassword;
    }




}


