package com.hp;
// Generated Jul 18, 2015 2:01:20 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Questions generated by hbm2java
 */
@Entity
@Table(name="questions"
    ,catalog="stp15_june"
)
public class Questions  implements java.io.Serializable {


     private Integer questionid;
     private String question;
     private String opt1;
     private String opt2;
     private String opt3;
     private String opt4;
     private String answer;

    public Questions() {
    }

    public Questions(String question, String opt1, String opt2, String opt3, String opt4, String answer) {
       this.question = question;
       this.opt1 = opt1;
       this.opt2 = opt2;
       this.opt3 = opt3;
       this.opt4 = opt4;
       this.answer = answer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="questionid", unique=true, nullable=false)
    public Integer getQuestionid() {
        return this.questionid;
    }
    
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    
    @Column(name="question", nullable=false, length=45)
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    
    @Column(name="opt1", nullable=false, length=45)
    public String getOpt1() {
        return this.opt1;
    }
    
    public void setOpt1(String opt1) {
        this.opt1 = opt1;
    }

    
    @Column(name="opt2", nullable=false, length=45)
    public String getOpt2() {
        return this.opt2;
    }
    
    public void setOpt2(String opt2) {
        this.opt2 = opt2;
    }

    
    @Column(name="opt3", nullable=false, length=45)
    public String getOpt3() {
        return this.opt3;
    }
    
    public void setOpt3(String opt3) {
        this.opt3 = opt3;
    }

    
    @Column(name="opt4", nullable=false, length=45)
    public String getOpt4() {
        return this.opt4;
    }
    
    public void setOpt4(String opt4) {
        this.opt4 = opt4;
    }

    
    @Column(name="answer", nullable=false, length=45)
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


