package com.hp;
// Generated Jul 18, 2015 2:01:20 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rate generated by hbm2java
 */
@Entity
@Table(name="rate"
    ,catalog="stp15_june"
)
public class Rate  implements java.io.Serializable {


     private String username;
     private String rate;

    public Rate() {
    }

    public Rate(String username, String rate) {
       this.username = username;
       this.rate = rate;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="rate", nullable=false, length=45)
    public String getRate() {
        return this.rate;
    }
    
    public void setRate(String rate) {
        this.rate = rate;
    }




}


